### ISSUE TITLE
check (and tune) responsive views

### ISSUE THREAD

**Issue by ax-sc** [desklab/gcampus#28]

**Comment by ax-sc** [comment]
I found a small issue with the token input at the login page for course tokens appearing at medium sized devices in landscape mode:

![image](https://user-images.githubusercontent.com/51637472/164018057-901a0ff8-c08d-4832-bfb8-02f29323dbce.png)

**Comment by ax-sc** [comment]
I fixed the token input field by reducing the `min-width` set in `gcampus/core/static_src/styles/_forms.scss` but i couldn´t find a size-combination the `min-width` actions does not step into action for the login at all, so i´m not sure which exact value we should choose for it (but it should be smaller than it is currently to fix the issue from the previous comment).

**Comment by jnsdrtlf** [comment]
@ax-sc for now most things have been implemented and I fixed many issues. Can you take a look at the current progress on the `main` branch? You'll have to rebuild the styles and JavaScript files with `npm run dev.once`.

The menu on mobile devices has less functionality because the authentication menu is missing. I was not happy with putting all menu items from the dropdown into the menu as they are somewhat redundant. But for now I think that is fine.

I did not update the login page yet, mainly because I was unsure whether it is worth the time. Didn't we plan to redo the login and error pages anyway?

**Comment by ax-sc** [comment]
Thanks @jnsdrtlf ! 

> The menu on mobile devices has less functionality because the authentication menu is missing. I was not happy with putting all menu items from the dropdown into the menu as they are somewhat redundant. But for now I think that is fine.

I like the menu and do not miss any important items in it. Just one idea to discuss: Did you consider dropping the legend of the map (measurement at running/flowing water) and putting the authentication menu there? In case we are leaving it as it is right now (which is okay to me), we maybe need to shorten the text part of the legend as it needs more than one line per item on small screens and therefore overflows the menu bar. 
 
> I did not update the login page yet, mainly because I was unsure whether it is worth the time. Didn't we plan to redo the login and error pages anyway?

Yes, thats probably right, no need the update them now / before we reorganised them. (They are also not to bad on small screens at the moment)

I found some minor issues on different views, testing on a 375x667 and 414x736 screen:
- [ ] course administration, first tab: no space between last document item and the bottom
- [ ] course administration, second tab: access key items need to much horizontal space
- [ ] calibration (with more then one calibration per param): no space between heading of second calibration and grpah of first calibration
- [ ] water detail: no vertical space between buttons and map
- [ ] measurement detail: no vertical space between buttons and map
- [ ] measurement list: no vertical space between search bar and buttons

**Comment by jnsdrtlf** [comment]
Thanks for your feedback! I have fixed the smaller issues and also the login and error pages. The fix was just a few lines so no additional effort :)

As for the title: I think putting the authentication menu there would also take up to much space and look a bit off. A title is useful to know on which page you are on so I would prefer to keep it this way. However, I agree that the map legend looks a bit off, especially when the screen is too small and the text overflows. But for now I would also leave it as it is, maybe we have a better idea in the future :)

I will close this issue for now and create a release to deploy the responsive layout 🥳
