### ISSUE TITLE
tool to calculate concentration from optical density

### ISSUE THREAD

**Issue by ax-sc** [desklab/gcampus#37]

**Comment by nlwach** [comment]
With 30eb01f the main functionality plus the plots are now done. The only thing that might be added are lines going from the circular indicator to the x/y axis and additional values in the plot. But IMO this is not really necessary since the indicator makes it fairly clear where the values in the concentration output come from...

**Comment by ax-sc** [comment]
Looks really nice at it is now, i think we do not need the lines for the moment. I summarized what we have discussed earlier today below as a short reminder what is still to do before we can close this issue.

- [ ] remove spinners for concentration field
- [ ] rename concentration field label to parameter name
- [ ] reorganize/add explanatory text
- [ ] limit OD axis to 1.5
- [ ] do we need non-linear calibrations? (@ax-sc)
