### ISSUE TITLE
 delete outdated documents

### ISSUE THREAD

**Issue by ax-sc** [desklab/gcampus#75]
We should be able to clear all cached documents in order to force rebuilding them (once requested again by a user) after changing the style/layout/included assets.

**Comment by jnsdrtlf** [comment]
It would be useful to modify this further as some documents are unreferenced but never deleted (due to performance reasons):

https://github.com/desklab/gcampus/blob/dc7bbcf86a74cca30b5c214d6289a797db83f13e/gcampus/core/receivers.py#L106-L108

So a task (because it may take a significant amount of time) that deletes all files that are no longer referenced may be useful here.

**Comment by ax-sc** [comment]
> It would be useful to modify this further as some documents are unreferenced but never deleted (due to performance reasons):

I did the same in dc7bbcf86a74cca30b5c214d6289a797db83f13e, so these files are also not deleted. Is there a way to provide some general actions in the admin interface, not related to a model? Then we could maybe include an `importwater` action as well?

**Comment by ax-sc** [comment]
What do you think about adding one step to the maintenance task to delete all document files which are no longer referenced?

**Comment by jnsdrtlf** [comment]
In principle, this could now be done by simply deleting the 'documents' directory.

Having an automated process for this is not easy as we would have to detect changes made to the document templates/css.

Instead, when changes require require a rebuild of all documents, it is easiest to SSH onto the server and delete the documents directory manually. Documents will then be automatically rebuild once they are requested.

I'm closing this for now, I think most problems in this issue have already been addressed.
